# Generated by Django 5.0.1 on 2024-02-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CONSULTORIOS',
            new_name='Consultorio',
        ),
        migrations.RenameModel(
            old_name='ESPECIALIDADES',
            new_name='Especialidad',
        ),
        migrations.RenameModel(
            old_name='PROFESIONALES',
            new_name='Profesional',
        ),
    ]
