# Generated by Django 5.0.1 on 2024-02-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_consultorios_consultorio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['nombre'], 'verbose_name': 'especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['profesion', 'apellido'], 'verbose_name': 'profesional', 'verbose_name_plural': 'Profesionales'},
        ),
    ]
